add tests
System-Genesis/basic-match pull request #1
Opened 2021-06-06 10:44 UTC by RoeiOren

Add test and redesign the code

2021-06-06 11:12 UTC, 770menahem commented on Dockerfile
> +WORKDIR /usr/src/app
npm i sepered for preformence

2021-06-06 11:16 UTC, 770menahem commented on src/config/validators.ts
> +export default (param: any) => {
move param to identityCard func, chnage name => id

2021-06-06 11:17 UTC, 770menahem commented on src/utils/matchFiles/basicFuncs.ts
>      validators(value).identityCard ? (matchedRecord.identityCard = value) : null;
fix

2021-06-06 11:18 UTC, 770menahem commented on src/utils/matchFiles/basicFuncs.ts
> +    validators(value).mobilePhone.test(value) ? (matchedRecord.mobilePhone = value) : null;
del value

2021-06-06 11:18 UTC, 770menahem commented on src/utils/matchFiles/basicFuncs.ts
> +    validators(value).phone.test(value) ? (matchedRecord.phone = value) : null;
''

2021-06-06 11:26 UTC, 770menahem commented on src/utils/matchFiles/matchAdNN.ts
>      let uniqueNum: string;
startWith()

2021-06-06 11:29 UTC, 770menahem commented on src/utils/matchFiles/matchAdNN.ts
>      let uniqueNum: string;
במ

2021-06-06 11:38 UTC, 770menahem commented on src/utils/matchFiles/matchAdNN.ts
> +                setIdentifierDUAndEntityType(matchedRecord, record[key]);
add to map

2021-06-06 11:41 UTC, 770menahem commented on src/utils/matchFiles/matchCity.ts
>  const isNumeric = (value: number | string) => {
move to utils file

2021-06-06 11:45 UTC, 770menahem commented on src/utils/matchFiles/matchCity.ts
>          if (matchedRecord.hierarchy[0] === '/') {
startwith

2021-06-06 11:46 UTC, 770menahem commented on src/utils/matchFiles/matchCity.ts
> +                setEntityTypeAndDU(matchedRecord, record[key]);
move to map

2021-06-06 11:51 UTC, 770menahem reviewed
sachtain

2021-06-06 22:24 UTC, NoamYes commented on .gitlab-ci.yml
> +    - docker:18.09-dind
what are these configurations?

2021-06-06 22:25 UTC, NoamYes commented on basic_match.env
> +PORT=8000
another env file?

2021-06-07 08:34 UTC, NoamYes commented on src/config/fieldNames.ts
>      personStatus: {
probably can delete

2021-06-07 08:36 UTC, NoamYes commented on src/matchFiles/basicFuncs.ts
> +    const date: Date | null = value && value !== 'לא ידוע' ? new Date(value) : null;
can be unknown? either delete or change to 'unknown'

2021-06-07 08:36 UTC, NoamYes commented on src/matchFiles/basicFuncs.ts
> +    const date: Date | null = value && value !== 'לא ידוע' ? new Date(value) : null;
add to fieldNames unknown

2021-06-07 08:41 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
> +const macthedRecordFN = fieldNames.matchedRecord;
=> matchRecordFieldNames

2021-06-07 08:49 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
>          return;
should log "the record with the userID...."

2021-06-07 08:50 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
>          uniqueNum = userID.toLowerCase().replace(fn.extension, '');
suffixID (?)

2021-06-07 08:52 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
> +const setHierarchyAndJob = (matchedRecord: matchedRecordType, hierarchy: string, record: any): void => {
any => record type?

2021-06-07 08:53 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
>      let hr: string[] = hierarchy.includes('\\')
add example and documentation

2021-06-07 08:54 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
> +    hr[0] === fieldNames.rootHierarchy.ourCompany ? null : hr.unshift(fieldNames.rootHierarchy.ourCompany);
doc if need to insert root

2021-06-07 08:54 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
>          return organizationName.trim();
deletes spaces?

2021-06-07 08:55 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
>      [fn.sAMAccountName, setIdentifierDUAndEntityType],
DU => DI/userID

2021-06-07 08:58 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
> +    const keys: string[] = Object.keys(record);
keys => fields/props assign

2021-06-07 08:58 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
> +        if (record[key] && record[key] !== 'לא ידוע') {
again, unknown

2021-06-07 11:47 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
> +                setHierarchyAndJob(matchedRecord, record[key], record);
i winder if there's another solution for the distinction of arguments

2021-06-07 11:47 UTC, NoamYes commented on src/matchFiles/matchAka.ts
> +const funcMap = new Map<string, (matchedRecord: matchedRecordType, value: string) => void>([
perhaps should rename to fieldFuncs?

2021-06-07 11:50 UTC, NoamYes commented on src/matchFiles/matchCity.ts
> +        // eslint-disable-next-line prefer-const
why disable prefer const, could be const

2021-06-07 11:52 UTC, NoamYes commented on src/matchFiles/matchCity.ts
> +const setEntityTypeAndDU = (matchedRecord: matchedRecordType, userID: string): void => {
DU => DI

2021-06-07 11:52 UTC, NoamYes commented on src/matchFiles/matchCity.ts
> +            return;
log isn't valid

2021-06-07 11:53 UTC, NoamYes commented on src/matchFiles/matchCity.ts
> +        // TO DO
don't forget unrecognized prefix

2021-06-07 11:53 UTC, NoamYes commented on src/matchFiles/matchCity.ts
> +        if (!matchedRecord[macthedRecordFN.job]) {
mactedRecordFN => new name

2021-06-07 11:55 UTC, NoamYes commented on src/matchFiles/matchCity.ts
> +    matchedRecord[macthedRecordFN.source] = record[fn.domains].includes(fn.domainNames.external)
according to airbnb standards?

2021-06-07 11:56 UTC, NoamYes commented on src/matchFiles/matchEs.ts
> +    let hr: string[] = value.split('/');
better add basic documentation to the hierarchy/job

2021-06-07 12:03 UTC, NoamYes commented on src/matchFiles/matchSf.ts
> +    matchedRecord.sex = value === sfSex[0] ? fn.sfSexValues[sfSex[0]] : fn.sfSexValues[sfSex[1]];
give it another thought

2021-06-07 12:09 UTC, NoamYes reviewed
continue

2021-06-07 12:17 UTC, RoeiOren commented on basic_match.env
> +PORT=8000
For the docker compose

2021-06-07 12:40 UTC, RoeiOren commented on src/matchFiles/matchAdNN.ts
> +                setHierarchyAndJob(matchedRecord, record[key], record);
I think there isn't

2021-06-13 07:57 UTC, NoamYes commented on src/config/fieldNames.ts
> +        phone: 'phone',
check that out

2021-06-13 07:59 UTC, NoamYes commented on src/index.ts
> +import { rabbitConect } from './rabbit';
fix n

2021-06-13 08:01 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
> +const setIdentifierDIAndEntityType = (matchedRecord: matchedRecordType, userID: string, runUID: string): void => {
dont forget about documentation

2021-06-13 08:03 UTC, NoamYes commented on src/matchFiles/basicFuncs.ts
> +export const setDischargeDay = (matchedRecord: matchedRecordType, value: string): void => {
document functions with essence

2021-06-13 08:11 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
> +const fn = fieldNames[fieldNames.dataSources.adNN];
fieldsNames dataSources => sources

2021-06-13 08:14 UTC, NoamYes commented on src/matchFiles/basicFuncs.ts
> +export const setField = (mathcedRecord: any, value: string, fieldName: string): void => {
type matched

2021-06-13 08:15 UTC, NoamYes commented on src/matchFiles/matchAdNN.ts
> +    matchedRecord.hierarchy = matchedRecord.hierarchy.replace(new RegExp('\u{200f}', 'g'), '');
docmentation

2021-06-13 08:19 UTC, NoamYes commented on src/matchFiles/matchAka.ts
> +const setPhone = (matchedRecord: matchedRecordType, phone: string, areaCode: string) => {
reduce areaCode and phone into one argument

2021-06-13 08:21 UTC, NoamYes commented on src/matchFiles/matchAka.ts
> +        }
buildEntity uses the source of the record, should add that anyway

2021-06-13 08:24 UTC, NoamYes commented on src/matchFiles/matchCity.ts
> +/* eslint-disable no-unused-expressions */
try to remove these exceptions and deal with them according to the documentation on airbnb standards

2021-06-13 08:32 UTC, NoamYes commented on tests/matchCity.test.ts
> +import { matchedRecord as matchedRecordType } from '../src/types/matchedRecord';
as i recommended to discuss/discover some interesting tests

2021-06-13 08:32 UTC, NoamYes reviewed
better

2021-06-23 11:48 UTC, Eli-BB8 commented on .env.dev
> +LOG_QUEUE=logger
change queue name

2021-06-23 11:52 UTC, Eli-BB8 commented on basic_match.env
> +LOG_QUEUE=logger
queue name

2021-06-23 11:55 UTC, Eli-BB8 commented on src/basicMatch.ts
> +export default (obj: queueObject): matchedRecordType => {
queueObject => record

2021-06-23 11:57 UTC, Eli-BB8 commented on src/basicMatch.ts
> +    validateRecord(matchedRecord);
validate and return only if DS exits, log error if get DS not existing

2021-06-23 12:00 UTC, Eli-BB8 commented on src/config/enums.ts
> +export const AKA_UNITS = [
move each source to json file,

2021-06-23 12:01 UTC, Eli-BB8 commented on src/config/index.ts
> +        logQueue: env.get('LOG_QUEUE').required().asString(),
nice

2021-06-23 12:03 UTC, Eli-BB8 commented on src/config/validators.ts
> +        identityCard: (idNumber: string): string | boolean | void => {
return bool

2021-06-23 12:10 UTC, Eli-BB8 commented on src/matchFiles/matchAdNN.ts
> +        return;
logError

2021-06-23 12:13 UTC, Eli-BB8 commented on src/matchFiles/matchAdNN.ts
> +    if (hierarchy.includes('-')) {
set lastIndex symbol to const

2021-06-23 12:16 UTC, Eli-BB8 commented on src/matchFiles/matchAdNN.ts
> +const fieldsFuncs = new Map<string, (matchedRecord: matchedRecordType, value: string) => void>([
setFIelds

2021-06-23 12:16 UTC, Eli-BB8 commented on src/matchFiles/matchAdNN.ts
> +const fieldsFuncs = new Map<string, (matchedRecord: matchedRecordType, value: string) => void>([
or else

2021-06-23 12:16 UTC, Eli-BB8 commented on src/matchFiles/matchAdNN.ts
> +    originalRecordFields.map((field: string) => {
forEach

2021-06-23 12:19 UTC, Eli-BB8 commented on src/matchFiles/matchAka.ts
> +                console.log(`${record[fn.areaCodeMobile]}-${record[field]}`);
delete log

2021-06-23 12:27 UTC, Eli-BB8 commented on src/matchFiles/matchEs.ts
> +        return;
logError

2021-06-23 12:29 UTC, Eli-BB8 commented on src/matchFiles/setField.ts
> +// Basic functions
delete all //

2021-06-23 12:30 UTC, Eli-BB8 commented on src/rabbit.ts
> +export const sendLog = async (level: string, message: string, system: string, service: string, extraFields?: any): Promise<void> => {
log to log file

2021-06-23 12:33 UTC, Eli-BB8 commented on src/validateRecord.ts
> +const validateRank = (matchedRecord: matchedRecordType, identifier: string): void => {
or change name or move delete from validate

2021-06-23 12:37 UTC, Eli-BB8 reviewed
look good

2021-06-27 11:50 UTC, DavidHeymann requested changes

2021-07-05 10:59 UTC, DavidHeymann approved these changes

2021-07-05 11:03 UTC, 770menahem approved these changes

2021-07-05 11:05 UTC, merged